### ISSUE TITLE
add icon to games on main menu

### ISSUE THREAD

**Issue by mozsarmate** [kir-dev/kir-kuty-next#6]
edit MenuItem component to achieve that

**Comment by bilalshaikh292** [comment]
heyy is the issue still open ? I would like to contribute ?

**Comment by mozsarmate** [comment]
We appreciate you reaching out, but we would like to assign tasks primarily among our own members.
If you really want to help, please look for issues with the 'help wanted' label. If we need outside help, we'll open an issue with that tag and describe our problem there.

Thanks!
